services:
  - type: web
    name: meet-jeff-olsen-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && yarn install && yarn build
    preDeployCommand: cd backend && npx prisma migrate deploy
    startCommand: node backend/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ALLOWED_ORIGIN
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: FEATURE_API_KEYS
        value: "true"
      - key: VITE_API_SLUG
        sync: false
      - key: VITE_API_KEY
        sync: false
      - key: VITE_BASE_URL
        sync: false
