import {
  READ_PROFILE_SCOPE,
  UPDATE_PROFILE_SCOPE,
  DELETE_PROFILE_SCOPE,
  READ_SESSION_SCOPE,
  UPDATE_SESSION_SCOPE,
  READ_VERIFICATION_CODE_SCOPE,
  CREATE_API_KEY_SCOPE,
  READ_API_KEY_SCOPE,
  READ_ITEM_SCOPE,
  CREATE_ITEM_SCOPE,
  DELETE_ITEM_SCOPE,
  UPDATE_ITEM_SCOPE,
  READ_TAG_SCOPE,
  READ_IMAGE_SCOPE,
  READ_COMPONENT_SCOPE,
  READ_FEED_SCOPE,
  CREATE_FEED_SCOPE,
  UPDATE_FEED_SCOPE,
  CREATE_COMPONENT_SCOPE,
  UPDATE_COMPONENT_SCOPE,
  CREATE_DATE_RANGE_SCOPE,
  READ_DATE_RANGE_SCOPE,
  UPDATE_DATE_RANGE_SCOPE,
  DELETE_DATE_RANGE_SCOPE,
  DELETE_FEED_SCOPE,
  DELETE_COMPONENT_SCOPE,
  READ_COMPONENT_TYPE_SCOPE,
} from "../config/scopes";

export const defaultProfileScope = () =>
  createScopeString([
    READ_PROFILE_SCOPE,
    UPDATE_PROFILE_SCOPE,
    DELETE_PROFILE_SCOPE,

    UPDATE_SESSION_SCOPE,
    READ_SESSION_SCOPE,

    READ_VERIFICATION_CODE_SCOPE,

    READ_API_KEY_SCOPE,
    CREATE_API_KEY_SCOPE,

    READ_TAG_SCOPE,

    READ_IMAGE_SCOPE,

    READ_COMPONENT_TYPE_SCOPE,

    CREATE_ITEM_SCOPE,
    READ_ITEM_SCOPE,
    UPDATE_ITEM_SCOPE,
    DELETE_ITEM_SCOPE,

    CREATE_DATE_RANGE_SCOPE,
    READ_DATE_RANGE_SCOPE,
    UPDATE_DATE_RANGE_SCOPE,
    DELETE_DATE_RANGE_SCOPE,

    READ_FEED_SCOPE,
    CREATE_FEED_SCOPE,
    UPDATE_FEED_SCOPE,
    DELETE_FEED_SCOPE,

    READ_COMPONENT_SCOPE,
    CREATE_COMPONENT_SCOPE,
    UPDATE_COMPONENT_SCOPE,
    DELETE_COMPONENT_SCOPE,
  ]);

export const defaultApiKeyScope = () =>
  createScopeString([
    READ_FEED_SCOPE,
    READ_ITEM_SCOPE,
    READ_COMPONENT_SCOPE,
    READ_COMPONENT_TYPE_SCOPE,
    READ_TAG_SCOPE,
    READ_IMAGE_SCOPE,
    READ_DATE_RANGE_SCOPE,
  ]);

export const API_KEY_SESSION = "API_KEY_SESSION";
export const PROFILE_SESSION = "PROFILE_SESSION";
export type ScopeType = typeof API_KEY_SESSION | typeof PROFILE_SESSION;

export const getScope = (scopeCode: ScopeType) => {
  const authScope =
    scopeCode === API_KEY_SESSION
      ? defaultApiKeyScope()
      : scopeCode === PROFILE_SESSION
        ? defaultProfileScope()
        : "";
  return authScope ? createScopeString([authScope]) : authScope;
};

const DELIMITER = " ";
export type JoinScopesArgs = string[];
export type SplitScopesArgs = string;

export const createScopeString = (scopes: JoinScopesArgs) =>
  scopes.join(DELIMITER);

export const parseScopeString = (scopes: SplitScopesArgs) =>
  scopes.split(DELIMITER);
